
services:
  terminal:
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    build:
      context: .
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./huggingface/:/root/.cache/huggingface/
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]