
services:
  terminal:
    build:
      context: .
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      -  ./:/app
      - ./huggingface/:/root/.cache/huggingface/
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]